---
X_No_Archive: Yes
abstract: 'Pure Perl BitTorrent Client'
author:
  - 'Sanko Robinson <sanko@cpan.org>'
build_requires:
  Module::Build::Tiny: '0'
  Test2::V1: '0'
configure_requires:
  Module::Build::Tiny: '0'
  perl: v5.42.0
dynamic_config: 0
generated_by: 'App::mii v1.0.0, CPAN::Meta::Converter version 2.150012'
keywords:
  - dht
  - kademlia
  - bittorrent
  - interplanetary
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Net-BitTorrent
no_index:
  directory:
    - t
    - xt
    - eg
optional_features:
  BEP44:
    description: 'BEP44: Storing arbitrary data in the DHT'
  mse:
    description: 'Protocol Encryption (MSE/PE) support'
    requires:
      Crypt::PK::DH: '0'
      Crypt::Stream::RC4: '0'
  upnp:
    description: 'UPnP port mapping support'
    requires:
      Acme::UPnP: '0'
provides:
  Net::BitTorrent:
    file: lib/Net/BitTorrent.pm
    version: v2.0.0
  Net::BitTorrent::DHT:
    file: lib/Net/BitTorrent/DHT.pm
    version: v2.0.6
  Net::BitTorrent::DHT::Peer:
    file: lib/Net/BitTorrent/DHT.pm
    version: v2.0.6
  Net::BitTorrent::DHT::Security:
    file: lib/Net/BitTorrent/DHT/Security.pm
    version: v2.0.6
  Net::BitTorrent::Emitter:
    file: lib/Net/BitTorrent/Emitter.pm
    version: v2.0.0
  Net::BitTorrent::Peer:
    file: lib/Net/BitTorrent/Peer.pm
    version: v2.0.0
  Net::BitTorrent::Protocol::BEP03:
    file: lib/Net/BitTorrent/Protocol/BEP03.pm
    version: v2.0.0
  Net::BitTorrent::Protocol::BEP03::Bencode:
    file: lib/Net/BitTorrent/Protocol/BEP03/Bencode.pm
    version: v2.0.1
  Net::BitTorrent::Protocol::BEP06:
    file: lib/Net/BitTorrent/Protocol/BEP06.pm
    version: v2.0.0
  Net::BitTorrent::Protocol::BEP09:
    file: lib/Net/BitTorrent/Protocol/BEP09.pm
    version: v2.0.0
  Net::BitTorrent::Protocol::BEP10:
    file: lib/Net/BitTorrent/Protocol/BEP10.pm
    version: v2.0.0
  Net::BitTorrent::Protocol::BEP11:
    file: lib/Net/BitTorrent/Protocol/BEP11.pm
    version: v2.0.0
  Net::BitTorrent::Protocol::BEP23:
    file: lib/Net/BitTorrent/Protocol/BEP23.pm
    version: v2.0.0
  Net::BitTorrent::Protocol::BEP52:
    file: lib/Net/BitTorrent/Protocol/BEP52.pm
    version: v2.0.0
  Net::BitTorrent::Protocol::BEP53:
    file: lib/Net/BitTorrent/Protocol/BEP53.pm
    version: v2.0.0
  Net::BitTorrent::Protocol::BEP55:
    file: lib/Net/BitTorrent/Protocol/BEP55.pm
    version: v2.0.0
  Net::BitTorrent::Protocol::HandshakeOnly:
    file: lib/Net/BitTorrent/Protocol/HandshakeOnly.pm
    version: v2.0.0
  Net::BitTorrent::Protocol::MSE:
    file: lib/Net/BitTorrent/Protocol/MSE.pm
    version: v2.0.0
  Net::BitTorrent::Protocol::MSE::KeyExchange:
    file: lib/Net/BitTorrent/Protocol/MSE/KeyExchange.pm
    version: v2.0.0
  Net::BitTorrent::Protocol::MSE::RC4:
    file: lib/Net/BitTorrent/Protocol/MSE/KeyExchange.pm
    version: v2.0.0
  Net::BitTorrent::Protocol::PeerHandler:
    file: lib/Net/BitTorrent/Protocol/PeerHandler.pm
    version: v2.0.0
  Net::BitTorrent::Protocol::Simulation:
    file: lib/Net/BitTorrent/Protocol/Simulation.pm
    version: v2.0.0
  Net::BitTorrent::Storage:
    file: lib/Net/BitTorrent/Storage.pm
    version: v2.0.0
  Net::BitTorrent::Storage::File:
    file: lib/Net/BitTorrent/Storage/File.pm
    version: v2.0.0
  Net::BitTorrent::Torrent:
    file: lib/Net/BitTorrent/Torrent.pm
    version: v2.0.0
  Net::BitTorrent::Torrent::Generator:
    file: lib/Net/BitTorrent/Torrent/Generator.pm
    version: v2.0.0
  Net::BitTorrent::Torrent::PiecePicker:
    file: lib/Net/BitTorrent/Torrent/PiecePicker.pm
    version: v2.0.0
  Net::BitTorrent::Tracker:
    file: lib/Net/BitTorrent/Tracker.pm
    version: v2.0.0
  Net::BitTorrent::Tracker::Base:
    file: lib/Net/BitTorrent/Tracker/Base.pm
    version: v2.0.0
  Net::BitTorrent::Tracker::HTTP:
    file: lib/Net/BitTorrent/Tracker/HTTP.pm
    version: v2.0.0
  Net::BitTorrent::Tracker::UDP:
    file: lib/Net/BitTorrent/Tracker/UDP.pm
    version: v2.0.0
  Net::BitTorrent::Tracker::WebSeed:
    file: lib/Net/BitTorrent/Tracker/WebSeed.pm
    version: v2.0.0
  Net::BitTorrent::Transport::TCP:
    file: lib/Net/BitTorrent/Transport/TCP.pm
    version: v2.0.0
  Net::BitTorrent::Types:
    file: lib/Net/BitTorrent/Types.pm
    version: v2.0.0
recommends:
  Acme::UPnP: '0'
  Crypt::PK::DH: '0'
  Crypt::Perl::Ed25519::PublicKey: '0'
  Crypt::Stream::RC4: '0'
  IO::Async: '0'
requires:
  Acme::Bitfield: '0'
  Acme::Selection::RarestFirst: '0'
  Acme::UPnP: '0'
  Algorithm::Kademlia: v1.0.1
  Algorithm::RateLimiter::TokenBucket: '0'
  Digest::Merkle::SHA256: '0'
  Digest::SHA: '0'
  HTTP::Tiny: '0'
  IO::Select: '0'
  IO::Socket::INET: '0'
  IO::Socket::IP: '0'
  Net::Multicast::PeerDiscovery: '0'
  Net::uTP: '0'
  Path::Tiny: '0'
  Socket: '0'
  URI::Escape: '0'
  perl: v5.42.0
resources:
  bugtracker: https://github.com/sanko/Net-BitTorrent.pm/issues
  homepage: https://github.com/sanko/Net-BitTorrent.pm
  license: http://www.perlfoundation.org/artistic_license_2_0
  repository: git://github.com/sanko/Net-BitTorrent.pm.git
version: v2.0.0
x_help_wanted:
  - Tester
  - Documenter
x_ignore:
  - .tidyallrc
  - .gitignore
  - .github/
  - .github/*
  - .github/**
  - .clang-format
x_serialization_backend: 'CPAN::Meta::YAML version 0.020'
x_static_install: 0
